### ISSUE TITLE
Can't find Translator using the example code

### ISSUE THREAD

**Issue by zydjohnHotmail** [franck-gaspoz/GTranslatorAPI#2]
Hello:
I want to test your code, I created one Console Project with Visual Studio 2022, targeting .NET 5.0. And I install nuget package:
PM> Install-Package GTranslatorAPI -Version 1.0.0
The following is the code:
using System;
using System.Threading.Tasks;
using GTranslatorAPI;

namespace GoogleTranslateAPI
{
    public class Program
    {
        static async Task Main(string[] args)
        {
            string s = "Hello world!";
            Console.WriteLine(s);

            var translator = new Translator();
            var result = await translator.TranslateAsync(Languages.en, Languages.es, s);

            Console.WriteLine(result.TranslatedText);

            Console.WriteLine(dbg);
        }
    }
}

But I got compiler error:
Error	CS0246	The type or namespace name 'Translator' could not be found
Error	CS0103	The name 'dbg' does not exist in the current context.
Let me know how I can fix the above issues.
Thanks,

**Comment by JaiperJonson1986** [comment]
me too, it looks like the author changed something and didn't leave any information about it

**Comment by zydjohnHotmail** [comment]
Useless translator, forget it!
